# [cameras.required]
# name = 'camera'

# [cameras.usb]
# id = 0

# [cameras.rtsp]
# address = '0.0.0.0'
# port = 80
# user = 'admin'
# password = '12345678'

[cameras.default]
scale = 1
controllable = false

[cameras.default.pid_x]
p = 0.45
i = 0.01
d = 0.05

[cameras.default.pid_y]
p = 0.3
i = 0.01
d = 0
